<template>
  <div id="app" class="small-container">
    <h1>Employees</h1>
    <!-- has App capture the emitted event -->
    <employee-form @add:employee="addEmployee" />

    <!-- an attribute that begins with a colon will allow you to pass data -->
    <employee-table :employees="employees" @delete:employee="deleteEmployee" />
  </div>
</template>

<script>
// @ is used to reference the src folder & all imported components must be added to components folder
import EmployeeTable from "@/components/EmployeeTable.vue";
import EmployeeForm from "@/components/EmployeeForm.vue";

export default {
  name: "app",
  components: {
    EmployeeTable,
    EmployeeForm,
  },
  data() {
    return {
      employees: [
        {
          id: 1,
          name: "Richard Hendricks",
          email: "richard@piedpiper.com",
        },
        {
          id: 2,
          name: "Bertram Gilfoyle",
          email: "gilfoyle@piedpiper.com",
        },
        {
          id: 3,
          name: "Dinesh Chugtai",
          email: "dinesh@piedpiper.com",
        },
      ],
    };
  },
  methods: {
    addEmployee(employee) {
      // next four lines are to give employees unique IDs, would be autogenerated with real db
      const lastId = this.employees.length > 0 ? this.employees[this.employees.length - 1].id : 0;
      const id = lastId + 1;
      const newEmployee = { ...employee, id };
      // would be this.employees = [...this.employees, employee] if using db
      this.employees = [...this.employees, newEmployee];
    },
    deleteEmployee(id) {
      this.employees = this.employees.filter((employee) => employee.id !== id);
    },
  },
};
</script>

<style>
button {
  background: #009435;
  border: 1px solid #009435;
}

.small-container {
  max-width: 680px;
}
</style>
